/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AvatarConfig {
  'accessory' : string,
  'outfit' : string,
  'color' : string,
  'bodyType' : string,
}
export interface ChatMessage {
  'content' : string,
  'sender' : string,
  'timestamp' : bigint,
}
export interface DreamJournalEntryView {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'authorName' : string,
  'author' : Principal,
  'likes' : Array<Principal>,
  'timestamp' : bigint,
  'isPublic' : boolean,
}
export interface Group {
  'creator' : Principal,
  'members' : Array<Principal>,
  'name' : string,
  'description' : string,
}
export interface StarDedication {
  'id' : bigint,
  'message' : string,
  'timestamp' : bigint,
  'dedicatorName' : string,
  'recipientName' : string,
  'dedicatedBy' : Principal,
}
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'joinDate' : bigint,
  'totalScore' : bigint,
  'currentZone' : string,
  'avatar' : AvatarConfig,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorldEventView {
  'id' : bigint,
  'startTime' : bigint,
  'title' : string,
  'endTime' : bigint,
  'createdBy' : string,
  'zone' : string,
  'description' : string,
  'attendees' : Array<Principal>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptFriendRequest' : ActorMethod<[Principal], undefined>,
  'addJournalEntry' : ActorMethod<[string, string, boolean], undefined>,
  'addQuest' : ActorMethod<[string, string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeQuest' : ActorMethod<[bigint], undefined>,
  'createEvent' : ActorMethod<
    [string, string, string, bigint, bigint],
    undefined
  >,
  'createGroup' : ActorMethod<[string, string], undefined>,
  'createProfile' : ActorMethod<[string, string], undefined>,
  'dedicateStar' : ActorMethod<[string, string], undefined>,
  'deleteJournalEntry' : ActorMethod<[bigint], undefined>,
  'getActiveEvents' : ActorMethod<[], Array<WorldEventView>>,
  'getAllEvents' : ActorMethod<[], Array<WorldEventView>>,
  'getAllGroups' : ActorMethod<[], Array<Group>>,
  'getAllStars' : ActorMethod<[], Array<StarDedication>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<UserProfile>>,
  'getMyJournalEntries' : ActorMethod<[], Array<DreamJournalEntryView>>,
  'getProfile' : ActorMethod<[Principal], UserProfile>,
  'getPublicJournalEntries' : ActorMethod<[], Array<DreamJournalEntryView>>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getZoneMessages' : ActorMethod<[string], Array<ChatMessage>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinGroup' : ActorMethod<[string], undefined>,
  'likeJournalEntry' : ActorMethod<[bigint], undefined>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'rsvpEvent' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCallerUserProfileBook' : ActorMethod<[UserProfile], UserProfile>,
  'sendFriendRequest' : ActorMethod<[Principal], undefined>,
  'sendMessage' : ActorMethod<[string], undefined>,
  'startQuest' : ActorMethod<[bigint], undefined>,
  'teleport' : ActorMethod<[string], undefined>,
  'updateAvatar' : ActorMethod<[AvatarConfig], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];