/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const WorldEventView = IDL.Record({
  'id' : IDL.Nat,
  'startTime' : IDL.Int,
  'title' : IDL.Text,
  'endTime' : IDL.Int,
  'createdBy' : IDL.Text,
  'zone' : IDL.Text,
  'description' : IDL.Text,
  'attendees' : IDL.Vec(IDL.Principal),
});
export const Group = IDL.Record({
  'creator' : IDL.Principal,
  'members' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const StarDedication = IDL.Record({
  'id' : IDL.Nat,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'dedicatorName' : IDL.Text,
  'recipientName' : IDL.Text,
  'dedicatedBy' : IDL.Principal,
});
export const AvatarConfig = IDL.Record({
  'accessory' : IDL.Text,
  'outfit' : IDL.Text,
  'color' : IDL.Text,
  'bodyType' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'joinDate' : IDL.Int,
  'totalScore' : IDL.Nat,
  'currentZone' : IDL.Text,
  'avatar' : AvatarConfig,
});
export const DreamJournalEntryView = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'authorName' : IDL.Text,
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'timestamp' : IDL.Int,
  'isPublic' : IDL.Bool,
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'sender' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'addJournalEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
  'addQuest' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeQuest' : IDL.Func([IDL.Nat], [], []),
  'createEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Int],
      [],
      [],
    ),
  'createGroup' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'dedicateStar' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteJournalEntry' : IDL.Func([IDL.Nat], [], []),
  'getActiveEvents' : IDL.Func([], [IDL.Vec(WorldEventView)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(WorldEventView)], ['query']),
  'getAllGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
  'getAllStars' : IDL.Func([], [IDL.Vec(StarDedication)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getMyJournalEntries' : IDL.Func(
      [],
      [IDL.Vec(DreamJournalEntryView)],
      ['query'],
    ),
  'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getPublicJournalEntries' : IDL.Func(
      [],
      [IDL.Vec(DreamJournalEntryView)],
      ['query'],
    ),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getZoneMessages' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinGroup' : IDL.Func([IDL.Text], [], []),
  'likeJournalEntry' : IDL.Func([IDL.Nat], [], []),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'rsvpEvent' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCallerUserProfileBook' : IDL.Func([UserProfile], [UserProfile], []),
  'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'sendMessage' : IDL.Func([IDL.Text], [], []),
  'startQuest' : IDL.Func([IDL.Nat], [], []),
  'teleport' : IDL.Func([IDL.Text], [], []),
  'updateAvatar' : IDL.Func([AvatarConfig], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const WorldEventView = IDL.Record({
    'id' : IDL.Nat,
    'startTime' : IDL.Int,
    'title' : IDL.Text,
    'endTime' : IDL.Int,
    'createdBy' : IDL.Text,
    'zone' : IDL.Text,
    'description' : IDL.Text,
    'attendees' : IDL.Vec(IDL.Principal),
  });
  const Group = IDL.Record({
    'creator' : IDL.Principal,
    'members' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const StarDedication = IDL.Record({
    'id' : IDL.Nat,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'dedicatorName' : IDL.Text,
    'recipientName' : IDL.Text,
    'dedicatedBy' : IDL.Principal,
  });
  const AvatarConfig = IDL.Record({
    'accessory' : IDL.Text,
    'outfit' : IDL.Text,
    'color' : IDL.Text,
    'bodyType' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'joinDate' : IDL.Int,
    'totalScore' : IDL.Nat,
    'currentZone' : IDL.Text,
    'avatar' : AvatarConfig,
  });
  const DreamJournalEntryView = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'authorName' : IDL.Text,
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'timestamp' : IDL.Int,
    'isPublic' : IDL.Bool,
  });
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'sender' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'addJournalEntry' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
    'addQuest' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeQuest' : IDL.Func([IDL.Nat], [], []),
    'createEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Int],
        [],
        [],
      ),
    'createGroup' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'dedicateStar' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteJournalEntry' : IDL.Func([IDL.Nat], [], []),
    'getActiveEvents' : IDL.Func([], [IDL.Vec(WorldEventView)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(WorldEventView)], ['query']),
    'getAllGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
    'getAllStars' : IDL.Func([], [IDL.Vec(StarDedication)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getMyJournalEntries' : IDL.Func(
        [],
        [IDL.Vec(DreamJournalEntryView)],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getPublicJournalEntries' : IDL.Func(
        [],
        [IDL.Vec(DreamJournalEntryView)],
        ['query'],
      ),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getZoneMessages' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinGroup' : IDL.Func([IDL.Text], [], []),
    'likeJournalEntry' : IDL.Func([IDL.Nat], [], []),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'rsvpEvent' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCallerUserProfileBook' : IDL.Func([UserProfile], [UserProfile], []),
    'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'sendMessage' : IDL.Func([IDL.Text], [], []),
    'startQuest' : IDL.Func([IDL.Nat], [], []),
    'teleport' : IDL.Func([IDL.Text], [], []),
    'updateAvatar' : IDL.Func([AvatarConfig], [], []),
  });
};

export const init = ({ IDL }) => { return []; };